# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jango/Templates/MCPI/modding/conveyors

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jango/Templates/MCPI/modding/conveyors

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jango/Templates/MCPI/modding/conveyors/CMakeFiles /home/jango/Templates/MCPI/modding/conveyors//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jango/Templates/MCPI/modding/conveyors/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named redstone

# Build rule for target.
redstone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redstone
.PHONY : redstone

# fast build rule for target.
redstone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/build
.PHONY : redstone/fast

src/animal-following.o: src/animal-following.cpp.o
.PHONY : src/animal-following.o

# target to build an object file
src/animal-following.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/animal-following.cpp.o
.PHONY : src/animal-following.cpp.o

src/animal-following.i: src/animal-following.cpp.i
.PHONY : src/animal-following.i

# target to preprocess a source file
src/animal-following.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/animal-following.cpp.i
.PHONY : src/animal-following.cpp.i

src/animal-following.s: src/animal-following.cpp.s
.PHONY : src/animal-following.s

# target to generate assembly for a file
src/animal-following.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/animal-following.cpp.s
.PHONY : src/animal-following.cpp.s

src/api.o: src/api.cpp.o
.PHONY : src/api.o

# target to build an object file
src/api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/api.cpp.o
.PHONY : src/api.cpp.o

src/api.i: src/api.cpp.i
.PHONY : src/api.i

# target to preprocess a source file
src/api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/api.cpp.i
.PHONY : src/api.cpp.i

src/api.s: src/api.cpp.s
.PHONY : src/api.s

# target to generate assembly for a file
src/api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/api.cpp.s
.PHONY : src/api.cpp.s

src/block_frame.o: src/block_frame.cpp.o
.PHONY : src/block_frame.o

# target to build an object file
src/block_frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/block_frame.cpp.o
.PHONY : src/block_frame.cpp.o

src/block_frame.i: src/block_frame.cpp.i
.PHONY : src/block_frame.i

# target to preprocess a source file
src/block_frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/block_frame.cpp.i
.PHONY : src/block_frame.cpp.i

src/block_frame.s: src/block_frame.cpp.s
.PHONY : src/block_frame.s

# target to generate assembly for a file
src/block_frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/block_frame.cpp.s
.PHONY : src/block_frame.cpp.s

src/bomb.o: src/bomb.cpp.o
.PHONY : src/bomb.o

# target to build an object file
src/bomb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/bomb.cpp.o
.PHONY : src/bomb.cpp.o

src/bomb.i: src/bomb.cpp.i
.PHONY : src/bomb.i

# target to preprocess a source file
src/bomb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/bomb.cpp.i
.PHONY : src/bomb.cpp.i

src/bomb.s: src/bomb.cpp.s
.PHONY : src/bomb.s

# target to generate assembly for a file
src/bomb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/bomb.cpp.s
.PHONY : src/bomb.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/commands.o: src/commands.cpp.o
.PHONY : src/commands.o

# target to build an object file
src/commands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/commands.cpp.o
.PHONY : src/commands.cpp.o

src/commands.i: src/commands.cpp.i
.PHONY : src/commands.i

# target to preprocess a source file
src/commands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/commands.cpp.i
.PHONY : src/commands.cpp.i

src/commands.s: src/commands.cpp.s
.PHONY : src/commands.s

# target to generate assembly for a file
src/commands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/commands.cpp.s
.PHONY : src/commands.cpp.s

src/conveyor.o: src/conveyor.cpp.o
.PHONY : src/conveyor.o

# target to build an object file
src/conveyor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/conveyor.cpp.o
.PHONY : src/conveyor.cpp.o

src/conveyor.i: src/conveyor.cpp.i
.PHONY : src/conveyor.i

# target to preprocess a source file
src/conveyor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/conveyor.cpp.i
.PHONY : src/conveyor.cpp.i

src/conveyor.s: src/conveyor.cpp.s
.PHONY : src/conveyor.s

# target to generate assembly for a file
src/conveyor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/conveyor.cpp.s
.PHONY : src/conveyor.cpp.s

src/dash.o: src/dash.cpp.o
.PHONY : src/dash.o

# target to build an object file
src/dash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/dash.cpp.o
.PHONY : src/dash.cpp.o

src/dash.i: src/dash.cpp.i
.PHONY : src/dash.i

# target to preprocess a source file
src/dash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/dash.cpp.i
.PHONY : src/dash.cpp.i

src/dash.s: src/dash.cpp.s
.PHONY : src/dash.s

# target to generate assembly for a file
src/dash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/dash.cpp.s
.PHONY : src/dash.cpp.s

src/ender_pearls.o: src/ender_pearls.cpp.o
.PHONY : src/ender_pearls.o

# target to build an object file
src/ender_pearls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/ender_pearls.cpp.o
.PHONY : src/ender_pearls.cpp.o

src/ender_pearls.i: src/ender_pearls.cpp.i
.PHONY : src/ender_pearls.i

# target to preprocess a source file
src/ender_pearls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/ender_pearls.cpp.i
.PHONY : src/ender_pearls.cpp.i

src/ender_pearls.s: src/ender_pearls.cpp.s
.PHONY : src/ender_pearls.s

# target to generate assembly for a file
src/ender_pearls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/ender_pearls.cpp.s
.PHONY : src/ender_pearls.cpp.s

src/init.o: src/init.cpp.o
.PHONY : src/init.o

# target to build an object file
src/init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/init.cpp.o
.PHONY : src/init.cpp.o

src/init.i: src/init.cpp.i
.PHONY : src/init.i

# target to preprocess a source file
src/init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/init.cpp.i
.PHONY : src/init.cpp.i

src/init.s: src/init.cpp.s
.PHONY : src/init.s

# target to generate assembly for a file
src/init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/init.cpp.s
.PHONY : src/init.cpp.s

src/jungle_tree.o: src/jungle_tree.cpp.o
.PHONY : src/jungle_tree.o

# target to build an object file
src/jungle_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/jungle_tree.cpp.o
.PHONY : src/jungle_tree.cpp.o

src/jungle_tree.i: src/jungle_tree.cpp.i
.PHONY : src/jungle_tree.i

# target to preprocess a source file
src/jungle_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/jungle_tree.cpp.i
.PHONY : src/jungle_tree.cpp.i

src/jungle_tree.s: src/jungle_tree.cpp.s
.PHONY : src/jungle_tree.s

# target to generate assembly for a file
src/jungle_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/jungle_tree.cpp.s
.PHONY : src/jungle_tree.cpp.s

src/nether_wand.o: src/nether_wand.cpp.o
.PHONY : src/nether_wand.o

# target to build an object file
src/nether_wand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/nether_wand.cpp.o
.PHONY : src/nether_wand.cpp.o

src/nether_wand.i: src/nether_wand.cpp.i
.PHONY : src/nether_wand.i

# target to preprocess a source file
src/nether_wand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/nether_wand.cpp.i
.PHONY : src/nether_wand.cpp.i

src/nether_wand.s: src/nether_wand.cpp.s
.PHONY : src/nether_wand.s

# target to generate assembly for a file
src/nether_wand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/nether_wand.cpp.s
.PHONY : src/nether_wand.cpp.s

src/oddly_bright_block.o: src/oddly_bright_block.cpp.o
.PHONY : src/oddly_bright_block.o

# target to build an object file
src/oddly_bright_block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/oddly_bright_block.cpp.o
.PHONY : src/oddly_bright_block.cpp.o

src/oddly_bright_block.i: src/oddly_bright_block.cpp.i
.PHONY : src/oddly_bright_block.i

# target to preprocess a source file
src/oddly_bright_block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/oddly_bright_block.cpp.i
.PHONY : src/oddly_bright_block.cpp.i

src/oddly_bright_block.s: src/oddly_bright_block.cpp.s
.PHONY : src/oddly_bright_block.s

# target to generate assembly for a file
src/oddly_bright_block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/oddly_bright_block.cpp.s
.PHONY : src/oddly_bright_block.cpp.s

src/pedestal.o: src/pedestal.cpp.o
.PHONY : src/pedestal.o

# target to build an object file
src/pedestal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/pedestal.cpp.o
.PHONY : src/pedestal.cpp.o

src/pedestal.i: src/pedestal.cpp.i
.PHONY : src/pedestal.i

# target to preprocess a source file
src/pedestal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/pedestal.cpp.i
.PHONY : src/pedestal.cpp.i

src/pedestal.s: src/pedestal.cpp.s
.PHONY : src/pedestal.s

# target to generate assembly for a file
src/pedestal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/pedestal.cpp.s
.PHONY : src/pedestal.cpp.s

src/pistons.o: src/pistons.cpp.o
.PHONY : src/pistons.o

# target to build an object file
src/pistons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/pistons.cpp.o
.PHONY : src/pistons.cpp.o

src/pistons.i: src/pistons.cpp.i
.PHONY : src/pistons.i

# target to preprocess a source file
src/pistons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/pistons.cpp.i
.PHONY : src/pistons.cpp.i

src/pistons.s: src/pistons.cpp.s
.PHONY : src/pistons.s

# target to generate assembly for a file
src/pistons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/pistons.cpp.s
.PHONY : src/pistons.cpp.s

src/redstone.o: src/redstone.cpp.o
.PHONY : src/redstone.o

# target to build an object file
src/redstone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/redstone.cpp.o
.PHONY : src/redstone.cpp.o

src/redstone.i: src/redstone.cpp.i
.PHONY : src/redstone.i

# target to preprocess a source file
src/redstone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/redstone.cpp.i
.PHONY : src/redstone.cpp.i

src/redstone.s: src/redstone.cpp.s
.PHONY : src/redstone.s

# target to generate assembly for a file
src/redstone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/redstone.cpp.s
.PHONY : src/redstone.cpp.s

src/rendering.o: src/rendering.cpp.o
.PHONY : src/rendering.o

# target to build an object file
src/rendering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/rendering.cpp.o
.PHONY : src/rendering.cpp.o

src/rendering.i: src/rendering.cpp.i
.PHONY : src/rendering.i

# target to preprocess a source file
src/rendering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/rendering.cpp.i
.PHONY : src/rendering.cpp.i

src/rendering.s: src/rendering.cpp.s
.PHONY : src/rendering.s

# target to generate assembly for a file
src/rendering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/rendering.cpp.s
.PHONY : src/rendering.cpp.s

src/tiny.o: src/tiny.cpp.o
.PHONY : src/tiny.o

# target to build an object file
src/tiny.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/tiny.cpp.o
.PHONY : src/tiny.cpp.o

src/tiny.i: src/tiny.cpp.i
.PHONY : src/tiny.i

# target to preprocess a source file
src/tiny.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/tiny.cpp.i
.PHONY : src/tiny.cpp.i

src/tiny.s: src/tiny.cpp.s
.PHONY : src/tiny.s

# target to generate assembly for a file
src/tiny.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redstone.dir/build.make CMakeFiles/redstone.dir/src/tiny.cpp.s
.PHONY : src/tiny.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... redstone"
	@echo "... src/animal-following.o"
	@echo "... src/animal-following.i"
	@echo "... src/animal-following.s"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/block_frame.o"
	@echo "... src/block_frame.i"
	@echo "... src/block_frame.s"
	@echo "... src/bomb.o"
	@echo "... src/bomb.i"
	@echo "... src/bomb.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/commands.o"
	@echo "... src/commands.i"
	@echo "... src/commands.s"
	@echo "... src/conveyor.o"
	@echo "... src/conveyor.i"
	@echo "... src/conveyor.s"
	@echo "... src/dash.o"
	@echo "... src/dash.i"
	@echo "... src/dash.s"
	@echo "... src/ender_pearls.o"
	@echo "... src/ender_pearls.i"
	@echo "... src/ender_pearls.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/jungle_tree.o"
	@echo "... src/jungle_tree.i"
	@echo "... src/jungle_tree.s"
	@echo "... src/nether_wand.o"
	@echo "... src/nether_wand.i"
	@echo "... src/nether_wand.s"
	@echo "... src/oddly_bright_block.o"
	@echo "... src/oddly_bright_block.i"
	@echo "... src/oddly_bright_block.s"
	@echo "... src/pedestal.o"
	@echo "... src/pedestal.i"
	@echo "... src/pedestal.s"
	@echo "... src/pistons.o"
	@echo "... src/pistons.i"
	@echo "... src/pistons.s"
	@echo "... src/redstone.o"
	@echo "... src/redstone.i"
	@echo "... src/redstone.s"
	@echo "... src/rendering.o"
	@echo "... src/rendering.i"
	@echo "... src/rendering.s"
	@echo "... src/tiny.o"
	@echo "... src/tiny.i"
	@echo "... src/tiny.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

